services:
  database:
    image: 'postgres:17'
    ports:
      - "5432:5432"
    env_file: ".env"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ${PWD}/pgadmin-data/:/var/lib/pgadmin/